apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  NEXT_PUBLIC_BACKEND_URL: "http://ec2-98-84-170-170.compute-1.amazonaws.com"
  NEXT_PUBLIC_WS_URL: "ws://ec2-34-201-99-188.compute-1.amazonaws.com"
