apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-container
          image: kush233/draw-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_PUBLIC_BACKEND_URL
            - name: NEXT_PUBLIC_WS_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_PUBLIC_WS_URL