apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: kush233/draw-frontend:49bba63e6a2f8e55b2d013c8658ccbf2a92631b2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://backend.default.svc.cluster.local"
            - name: NEXT_PUBLIC_WS_URL
              value: "ws://wsbackend.default.svc.cluster.local"
