apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  NEXT_PUBLIC_BACKEND_URL: aHR0cDovL2VjMi05OC04NC0xNzAtMTcwLmNvbXB1dGUtMS5hbWF6b25hd3MuY29t
  NEXT_PUBLIC_WS_URL: d3M6Ly9lYzItMzQtMjAxLTk5LTE4OC5jb21wdXRlLTEuYW1hem9uYXdzLmNvbQ==
