name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}
          
    - name: Doctl auth
      run:  doctl auth init --access-token "${{ secrets.DO_ACCESS_TOKEN }}"
    
    - name: Get KubeConfig
      run: doctl kubernetes cluster kubeconfig save draw-app
    
    - name: Kubectl setup
      run: azure/setup-kubectl@v3
    
    - name: Update deployment
      run: |
          kubectl set image deployment/web-app web-container=kush233/draw-frontend:latest
          kubectl rollout status deployment/web-app 
            


 
